name = "mock-edevlet-kapisi"
main = "build/mock-edevlet-kapisi.js"
route = { pattern = "mock-edevlet-kapisi.kimlikdao.net", custom_domain = true }

compatibility_date = "2023-01-01"
workers_dev = false
usage_model = "bundled"
no_bundle = true
minify = false
send_metrics = false
node_compat = false
