type = "javascript"
account_id = "8f0c2f2271ff857947d9a5b2c38595a0"
zone_id = "77679a8547af21fab1fb07bd0425c6f0"
compatibility_date = "2022-04-14"

name = "mock-oauth2"
workers_dev = false
route = "https://mock-oauth2.kimlikdao.net/*"

[env.dev]
name = "mock-oauth2-dev"
workers_dev = true
route = ""
